name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install required packages
      run: sudo apt-get -y install ocaml ocaml-dune ocaml-odoc
    - name: Install yaml
      run: |
        cd /tmp
        sudo apt-get -y install libctypes-ocaml-dev libppx-sexp-conv-ocaml-dev libbos-ocaml-dev libsexplib-ocaml-dev libdune-ocaml-dev 
        git clone https://github.com/avsm/ocaml-yaml.git
        cd ocaml-yaml
        make
        sudo make install
    - name: Build
      run: dune build
    - name: Test
      run: dune runtest
    - name: Build doc
      run: dune build @doc
    # - name: Upload website artifact
      # uses: actions/upload-pages-artifact@v2
      # with:
        # path: docs
  # deploy:
    # needs: build
    # permissions:
      # pages: write
      # id-token: write
    # environment:
      # name: github-pages
      # url: ${{ steps.deployment.outputs.page_url }}
    # runs-on: ubuntu-latest
    # steps:
      # - name: Deploy website
        # id: deployment
        # uses: actions/deploy-pages@v2
